name: Chris Cesare | Science Writer
email: me@chriscesare.com
twitter_username: chriscesare
github_username: ccesare

markdown: kramdown

collections:
  clips:
    output: false
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title.html

maxclips: 5
url: localhost

sass:
  sass_dir: _sass
