name: Chris Cesare | Science Writer
email: me@chriscesare.com
twitter_username: chriscesare
github_username: ccesare
linkedin_username: chriscesare

source: src
destination: _site

sass_dir: src/_sass

markdown: kramdown
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  clips:
    output: false
  outlets:
    output: true
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title.html

maxclips: 5
url: localhost

