name: Chris Cesare | Science Writer
email: me@chriscesare.com
twitter_username: chriscesare
github_username: ccesare

markdown: kramdown

collections:
  - clips

permalink: /blog/:year/:month/:day/:title
