name: Chris Cesare | Science Writer
email: me@chriscesare.com
twitter_username: chriscesare
github_username: ccesare
linkedin_username: chriscesare

sass:
  sass_dir: _sass

exclude: ['node_modules', '.eslintrc.json', 'package-lock.json', 'package.json', 'README.md', 'webpack.config.js', 'webpack', 'CNAME']

markdown: kramdown
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  clips:
    output: false
  outlets:
    output: true
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title.html

maxclips: 5
url: localhost

