name: Chris Cesare | Science Writer
email: me@chriscesare.com
twitter_username: chriscesare
github_username: ccesare

markdown: kramdown

collections:
  clips:
    output: false

permalink: /blog/:year/:month/:day/:title

maxclips: 5
url: localhost

sass:
  sass_dir: _sass
